#+title: Comparatives
#+date: 2022-08-12
* Use
- Use the comparative form to talk about how two things are different. Comparative adjectives are used to compare differences between the two objects they modify (larger, smaller, faster, higher). They are used in sentences where two nouns are compared, in this pattern:
  - *Noun (subject) + verb + comparative adjective + than + noun (object).*
    - /I am taller than you/.
    - /This book is thicker than that one/.
- We use comparative adjectives when talking about two things (not three or more things).
- Add *than* after a comparative adjective to compare one thing with another. However, this is not always necessary.
  - /My house is smaller than yours/.
* Form
** Short
1) If an adjective has one syllable, add *er* to the end. If it ends in *e* already, just add *r*.
   - tall => taller
   - nice => nicer
   - thick => thicker
   - late => later
2) If an adjective ends in *one vowel and one consonant*, write the consonant again, then write *er*. But never write a *w* twice.
   - big => bigger
   - new => newer (NOT newwer)
   - thin => thinner
   - slow => slower (NOT slowwer)
   - slim => slimmer
   - /My brother is _thinner_ than me/.
3) If an adjective has two syllables and ends in *y*, change the y to *i* and add *er*.
   - funny => funnier
   - silly => sillier
   - /Which of these books is _funnier_?/
4) Some adjectives have irregular superlative forms. These are listed below.
   - good => better
   - bad => worse
   - far => further
** Long
1) If an adjective has two syllables and not ends in *y* or all adjectives of 3 or more syllables.
   - modern => more modern
   - expensive => more expensive
* Examples
- John is 1m80. He is tall. But Chris is 1m85. He is *taller* than John.
- America is big. But Russia is *bigger*.
- I want to have a *more powerful* computer.
- Is French *more difficult* than English?
- Mars is *smaller* than Earth.
- Mars is *more distant* from the Sun.
