#+title: Crucial preparation to guarantee your fluency

* Introduction to chapter 01
** 3 Keys to becoming fluent in English
*** Daily exposure
Consumir inglés  escrito y hablado  *a un  nivel comprensible*, todos  los días.
Esto permitirá poder entender todo lo que escucho, poder dejar de traducir en mi
cabeza, poder pensar en ingles y poder hablar ingles sin atascarme.
- Cause: Consuming the language
- Effect: Speaking in the language
*** Expanding vocabulary
Aprende palabras  nuevas cada día.  Es muy  importante aprender las  palabras en
frases  y no  individualmente. Aprendemos  palabras  en frases  para aprender  e
interiorizar simultáneamente estructuras gramaticales.
- 300 words: Survival level
- 3000 words: Conversational level, para cualquier idioma
- 6000+ words: Fluent level
- 15000-20000 words: Native speaker
*** Long-term consistency
Si no soy consistente no voy a conseguir dominar el inglés. Lo que se debe hacer
es  crear sistemas  que garanticen  que nunca  deje de  aprender y  minimizar la
cantidad de días libres que tengamos.
