#+title: Crucial preparation to guarantee your fluency

* Introduction to chapter 01
** 3 Keys to becoming fluent in English
*** Daily exposure
- Consumir inglés escrito  y hablado *a un nivel comprensible*,  todos los días.
  Esto permitirá poder entender todo lo  que escucho, poder dejar de traducir en
  mi cabeza, poder pensar en ingles y poder hablar ingles sin atascarme.
  - Cause: Consuming the language
  - Effect: Speaking in the language
*** Expanding vocabulary
- Aprende palabras nuevas  cada día. Es muy importante aprender  las palabras en
  frases y  no individualmente.  Aprendemos palabras en  frases para  aprender e
  interiorizar simultáneamente  estructuras gramaticales. - 300  words: Survival
  level.
  - 3000 words: Conversational level, para cualquier idioma
  - 6000+ words: Fluent level
  - 15000-20000 words: Native speaker
*** Long-term consistency
- Si no  soy consistente no voy  a conseguir dominar  el inglés. Lo que  se debe
  hacer es crear sistemas que garanticen  que nunca deje de aprender y minimizar
  la cantidad de días  libres que tengamos. Es muy importante  no saltarse ni un
  día, y  es más  importante estudiar todos  los días que  estudiar mucho  en un
  mismo día.
** Empezamos con  la exposición diaria, el  vocabulario o la constancia  a largo plazo?
- Debemos empezar  con la  exposición diaria.  Se debe crear  un sistema  que me
  obligue a estudiar hasta que haya creado ese hábito que lo hace automático. La
  verdadera razón por la que las personas  fracasan en un curso es porque no han
  construido un sistema que prácticamente hará imposible que se detengan.
** Objetivo del capítulo 1: Establecer sistemas para maximizar la productividad
- Para maximizar la motivación y la consistencia  a lo largo del curso hasta que
  aprender cada día se convierta en un hábito que no pueda romper y así nunca me
  rendiré.
** Estrategia del capítulo 1
1. Analizar mi PORQUÉ, Cual es mi proposito para aprender inglés?. Para aumentar
   la motivación, la ilusión y la disciplina todos los días.
2. Establece tus objetivos y firma contratos de responsabilidad con tus amigos y
   familiares para maximizar el compromiso.
3. Consigue    que  hablantes   nativos  de  inglés   me  ayuden   y  practiquen
   conversaciones con migo GRATIS!.
4. Unirme a  un  grupo de  responsabilidad formado  por  otros estudiantes  para
   obtener más apoyo y confianza.
